// Phidgets/4b_React/app/routes/example3.tsx
import { useRef, useState } from "react";
import type { Route } from "./+types/example3";
import "../phidget-examples.css";

export function meta({}: Route.MetaArgs) {
  return [{ title: "Phidget Button + Voltage Ratio + Digital Output" }];
}

export default function Example3() {
  // Form fields
  const [serverAddress, setServerAddress] = useState("localhost");
  const [serverPort, setServerPort] = useState("8989");

  // Connection + display state
  const [isConnected, setIsConnected] = useState(false);
  const [isButtonPressed, setIsButtonPressed] = useState(false);
  const [voltageRatio, setVoltageRatio] = useState<number | null>(null);
  const [isOutputOn, setIsOutputOn] = useState(false);
  const [rawState, setRawState] = useState<unknown>("Waiting for connection...");

  // The Phidget channel objects — kept in refs so re-renders don't recreate them
  const digitalInputRef = useRef<phidget22.DigitalInput | null>(null);
  const voltageRatioInputRef = useRef<phidget22.VoltageRatioInput | null>(null);
  const digitalOutputRef = useRef<phidget22.DigitalOutput | null>(null);

  function updateRawStatePanel(stateObject: unknown) {
    setRawState(stateObject);
  }

  async function connectToPhidgetServer(address: string, port: number) {
    const connection = new window.phidget22.NetworkConnection({
      hostname: address,
      port: port,
      onError: (code, message) => updateRawStatePanel({ connectionError: { code, message } }),
      onConnect: () => updateRawStatePanel({ status: "Connected" }),
      onDisconnect: () => {
        setIsConnected(false);
        updateRawStatePanel({ status: "Disconnected from server" });
      },
    });

    await connection.connect();

    const digitalInput = new window.phidget22.DigitalInput();
    digitalInputRef.current = digitalInput;

    digitalInput.isHubPortDevice = true;
    digitalInput.hubPort = 0;

    // Any channel on any hub connected to the server — adjust if you need
    // to target a specific device/channel.
    digitalInput.onAttach = () => {
      updateRawStatePanel({
        status: "Attached",
        deviceName: digitalInput.deviceName,
        serialNumber: digitalInput.deviceSerialNumber,
        channel: digitalInput.channel,
        state: digitalInput.state,
      });
      setIsButtonPressed(digitalInput.state === true);
    };

    digitalInput.onDetach = () => {
      updateRawStatePanel({ status: "Device detached" });
      setIsButtonPressed(false);
    };

    digitalInput.onStateChange = (state) => {
      setIsButtonPressed(!state);
      updateRawStatePanel({
        status: "State change",
        deviceName: digitalInput.deviceName,
        serialNumber: digitalInput.deviceSerialNumber,
        channel: digitalInput.channel,
        state,
        timestamp: new Date().toISOString(),
      });
    };

    await digitalInput.open(5000);

    const voltageRatioInput = new window.phidget22.VoltageRatioInput();
    voltageRatioInputRef.current = voltageRatioInput;

    voltageRatioInput.isHubPortDevice = true;
    voltageRatioInput.hubPort = 0;

    // Any channel on any hub connected to the server — adjust if you need
    // to target a specific device/channel.
    voltageRatioInput.onAttach = () => {
      updateRawStatePanel({
        status: "Attached",
        deviceName: voltageRatioInput.deviceName,
        serialNumber: voltageRatioInput.deviceSerialNumber,
        channel: voltageRatioInput.channel,
        voltageRatio: voltageRatioInput.voltageRatio,
      });
      setVoltageRatio(voltageRatioInput.voltageRatio);
    };

    voltageRatioInput.onDetach = () => {
      updateRawStatePanel({ status: "Device detached" });
      setVoltageRatio(null);
    };

    voltageRatioInput.onVoltageRatioChange = (ratio) => {
      setVoltageRatio(ratio);
      updateRawStatePanel({
        status: "Voltage ratio change",
        deviceName: voltageRatioInput.deviceName,
        serialNumber: voltageRatioInput.deviceSerialNumber,
        channel: voltageRatioInput.channel,
        voltageRatio: ratio,
        timestamp: new Date().toISOString(),
      });
    };

    await voltageRatioInput.open(5000);

    const digitalOutput = new window.phidget22.DigitalOutput();
    digitalOutputRef.current = digitalOutput;

    digitalOutput.isHubPortDevice = true;
    digitalOutput.hubPort = 0;

    // Any channel on any hub connected to the server — adjust if you need
    // to target a specific device/channel.
    digitalOutput.onAttach = () => {
      updateRawStatePanel({
        status: "Attached",
        deviceName: digitalOutput.deviceName,
        serialNumber: digitalOutput.deviceSerialNumber,
        channel: digitalOutput.channel,
        state: digitalOutput.state,
      });
      setIsOutputOn(digitalOutput.state === true);
    };

    digitalOutput.onDetach = () => {
      updateRawStatePanel({ status: "Device detached" });
      setIsOutputOn(false);
    };

    await digitalOutput.open(5000);

    setIsConnected(true);
  }

  async function disconnectFromPhidgetServer() {
    if (digitalInputRef.current) {
      try {
        await digitalInputRef.current.close();
      } catch (error) {
        // Channel may already be closed — nothing to do here.
      }
      digitalInputRef.current = null;
    }
    if (voltageRatioInputRef.current) {
      try {
        await voltageRatioInputRef.current.close();
      } catch (error) {
        // Channel may already be closed — nothing to do here.
      }
      voltageRatioInputRef.current = null;
    }
    if (digitalOutputRef.current) {
      try {
        await digitalOutputRef.current.close();
      } catch (error) {
        // Channel may already be closed — nothing to do here.
      }
      digitalOutputRef.current = null;
    }
    setIsButtonPressed(false);
    setVoltageRatio(null);
    setIsOutputOn(false);
    setIsConnected(false);
    updateRawStatePanel({ status: "Disconnected" });
  }

  async function handleConnectSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const address = serverAddress.trim();
    const port = parseInt(serverPort, 10);

    try {
      updateRawStatePanel({ status: "Connecting..." });
      await connectToPhidgetServer(address, port);
    } catch (error) {
      updateRawStatePanel({ connectionError: String(error) });
      setIsConnected(false);
    }
  }

  // Toggle the digital output each time the button is pressed
  async function handleOutputButtonClick() {
    const digitalOutput = digitalOutputRef.current;
    if (!digitalOutput) {
      return;
    }

    const nextState = !(digitalOutput.state === true);

    try {
      await digitalOutput.setState(nextState);
      setIsOutputOn(nextState);
      updateRawStatePanel({
        status: "State change",
        deviceName: digitalOutput.deviceName,
        serialNumber: digitalOutput.deviceSerialNumber,
        channel: digitalOutput.channel,
        state: nextState,
        timestamp: new Date().toISOString(),
      });
    } catch (error) {
      updateRawStatePanel({ setStateError: String(error) });
    }
  }

  // Voltage ratios from this sensor type range roughly 0 - 1
  const clampedRatio = voltageRatio === null ? 0 : Math.min(Math.max(voltageRatio, 0), 1);

  return (
    <div className="phidget-page">
      <h1>Phidget Button + Voltage Ratio + Digital Output</h1>

      <section>
        <form className="connection-form" onSubmit={handleConnectSubmit}>
          <label>
            Server address
            <input
              type="text"
              value={serverAddress}
              onChange={(event) => setServerAddress(event.target.value)}
              disabled={isConnected}
            />
          </label>
          <label>
            Port
            <input
              type="number"
              value={serverPort}
              onChange={(event) => setServerPort(event.target.value)}
              disabled={isConnected}
              style={{ width: "80px" }}
            />
          </label>
          <button type="submit" disabled={isConnected}>
            Connect
          </button>
          <button type="button" disabled={!isConnected} onClick={disconnectFromPhidgetServer}>
            Disconnect
          </button>
        </form>
        <div className="status-line">
          Status: <span className={isConnected ? "connected" : "disconnected"}>
            {isConnected ? "Connected" : "Disconnected"}
          </span>
        </div>
      </section>

      <section>
        <h2>Button State</h2>
        <div id="buttonVisual" className={isButtonPressed ? "pressed" : "neutral"}>
          {isButtonPressed ? "PRESSED" : "NEUTRAL"}
        </div>
      </section>

      <section>
        <h2>Voltage Ratio</h2>
        <div id="ratioVisual">
          <div id="ratioValue">{voltageRatio === null ? "--" : voltageRatio.toFixed(4)}</div>
          <div id="ratioBarTrack">
            <div id="ratioBarFill" style={{ width: `${clampedRatio * 100}%` }} />
          </div>
        </div>
      </section>

      <section>
        <h2>Digital Output</h2>
        <button
          id="outputButton"
          type="button"
          className={isOutputOn ? "on" : "off"}
          disabled={!isConnected}
          onClick={handleOutputButtonClick}
        >
          {isOutputOn ? "ON" : "OFF"}
        </button>
      </section>

      <section>
        <h2>Raw Phidget State</h2>
        <div id="rawStatePanel">
          {typeof rawState === "string" ? rawState : JSON.stringify(rawState, null, 2)}
        </div>
      </section>
    </div>
  );
}

// Phidgets/4c_Angular/src/app/example3/example3.ts
import { Component, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';

declare const phidget22: any;

@Component({
  selector: 'app-example3',
  imports: [FormsModule],
  templateUrl: './example3.html',
  styleUrls: ['../phidget-shared.css', './example3.css'],
})
export class Example3 {
  // Form state, bound to the connection inputs via ngModel
  serverAddress = signal('localhost');
  serverPort = signal(8989);

  // Connection + hardware state, read by the template
  connected = signal(false);
  statusText = signal('Disconnected');
  outputOn = signal(false);
  rawState = signal('Waiting for connection...');

  // Phidget object — created fresh on each connection attempt
  private digitalOutput: any = null;

  async connect(): Promise<void> {
    this.updateRawState({ status: 'Connecting...' });

    try {
      const connection = new phidget22.NetworkConnection({
        hostname: this.serverAddress(),
        port: this.serverPort(),
        onError: (code: number, message: string) =>
          this.updateRawState({ connectionError: { code, message } }),
        onConnect: () => this.updateRawState({ status: 'Connected' }),
        onDisconnect: () => {
          this.setConnected(false);
          this.updateRawState({ status: 'Disconnected from server' });
        },
      });

      await connection.connect();

      this.digitalOutput = new phidget22.DigitalOutput();

      this.digitalOutput.isHubPortDevice = false;
      this.digitalOutput.hubPort = 0;
      this.digitalOutput.channel = 0;

      // Any channel on any hub connected to the server — adjust if you need
      // to target a specific device/channel.
      this.digitalOutput.onAttach = () => {
        this.updateRawState({
          status: 'Attached',
          deviceName: this.digitalOutput.deviceName,
          serialNumber: this.digitalOutput.deviceSerialNumber,
          channel: this.digitalOutput.channel,
          state: this.digitalOutput.state,
        });
        this.outputOn.set(this.digitalOutput.state === true);
      };

      this.digitalOutput.onDetach = () => {
        this.updateRawState({ status: 'Device detached' });
        this.outputOn.set(false);
      };

      await this.digitalOutput.open(5000);

      this.setConnected(true);
    } catch (error) {
      this.updateRawState({ connectionError: String(error) });
      this.setConnected(false);
    }
  }

  async disconnect(): Promise<void> {
    if (this.digitalOutput) {
      try {
        await this.digitalOutput.close();
      } catch {
        // Channel may already be closed — nothing to do here.
      }
      this.digitalOutput = null;
    }

    this.outputOn.set(false);
    this.setConnected(false);
    this.updateRawState({ status: 'Disconnected' });
  }

  // Toggle the digital output each time the button is pressed
  async toggleOutput(): Promise<void> {
    if (!this.digitalOutput) {
      return;
    }

    const nextState = !this.digitalOutput.state;

    try {
      await this.digitalOutput.setState(nextState);
      this.outputOn.set(nextState);
      this.updateRawState({
        status: 'State change',
        deviceName: this.digitalOutput.deviceName,
        serialNumber: this.digitalOutput.deviceSerialNumber,
        channel: this.digitalOutput.channel,
        state: nextState,
        timestamp: new Date().toISOString(),
      });
    } catch (error) {
      this.updateRawState({ setStateError: String(error) });
    }
  }

  private setConnected(isConnected: boolean): void {
    this.connected.set(isConnected);
    this.statusText.set(isConnected ? 'Connected' : 'Disconnected');
  }

  private updateRawState(stateObject: unknown): void {
    this.rawState.set(JSON.stringify(stateObject, null, 2));
  }
}
