// Phidgets/4c_Angular/src/app/example1/example1.ts
import { Component, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';

declare const phidget22: any;

@Component({
  selector: 'app-example1',
  imports: [FormsModule],
  templateUrl: './example1.html',
  styleUrls: ['../phidget-shared.css', './example1.css'],
})
export class Example1 {
  // Form state, bound to the connection inputs via ngModel
  serverAddress = signal('localhost');
  serverPort = signal(8989);

  // Connection + hardware state, read by the template
  connected = signal(false);
  statusText = signal('Disconnected');
  buttonPressed = signal(false);
  rawState = signal('Waiting for connection...');

  // Phidget object — created fresh on each connection attempt
  private digitalInput: any = null;

  async connect(): Promise<void> {
    this.updateRawState({ status: 'Connecting...' });

    try {
      const connection = new phidget22.NetworkConnection({
        hostname: this.serverAddress(),
        port: this.serverPort(),
        onError: (code: number, message: string) =>
          this.updateRawState({ connectionError: { code, message } }),
        onConnect: () => this.updateRawState({ status: 'Connected' }),
        onDisconnect: () => {
          this.setConnected(false);
          this.updateRawState({ status: 'Disconnected from server' });
        },
      });

      await connection.connect();

      this.digitalInput = new phidget22.DigitalInput();

      this.digitalInput.isHubPortDevice = true;
      this.digitalInput.hubPort = 0;

      // Any channel on any hub connected to the server — adjust if you need
      // to target a specific device/channel.
      this.digitalInput.onAttach = () => {
        this.updateRawState({
          status: 'Attached',
          deviceName: this.digitalInput.deviceName,
          serialNumber: this.digitalInput.deviceSerialNumber,
          channel: this.digitalInput.channel,
          state: this.digitalInput.state,
        });
        this.buttonPressed.set(this.digitalInput.state === true);
      };

      this.digitalInput.onDetach = () => {
        this.updateRawState({ status: 'Device detached' });
        this.buttonPressed.set(false);
      };

      this.digitalInput.onStateChange = (state: boolean) => {
        this.buttonPressed.set(!state);
        this.updateRawState({
          status: 'State change',
          deviceName: this.digitalInput.deviceName,
          serialNumber: this.digitalInput.deviceSerialNumber,
          channel: this.digitalInput.channel,
          state,
          timestamp: new Date().toISOString(),
        });
      };

      await this.digitalInput.open(5000);

      this.setConnected(true);
    } catch (error) {
      this.updateRawState({ connectionError: String(error) });
      this.setConnected(false);
    }
  }

  async disconnect(): Promise<void> {
    if (this.digitalInput) {
      try {
        await this.digitalInput.close();
      } catch {
        // Channel may already be closed — nothing to do here.
      }
      this.digitalInput = null;
    }

    this.buttonPressed.set(false);
    this.setConnected(false);
    this.updateRawState({ status: 'Disconnected' });
  }

  private setConnected(isConnected: boolean): void {
    this.connected.set(isConnected);
    this.statusText.set(isConnected ? 'Connected' : 'Disconnected');
  }

  private updateRawState(stateObject: unknown): void {
    this.rawState.set(JSON.stringify(stateObject, null, 2));
  }
}

// Phidgets/4b_React/app/routes/example1.tsx
import { useRef, useState } from "react";
import * as phidget22 from "phidget22";
import type { Route } from "./+types/example1";
import "../phidget-examples.css";

export function meta({}: Route.MetaArgs) {
  return [{ title: "Phidget Button Monitor" }];
}

export default function Example1() {
  // Form fields
  const [serverAddress, setServerAddress] = useState("localhost");
  const [serverPort, setServerPort] = useState("8989");

  // Connection + display state
  const [isConnected, setIsConnected] = useState(false);
  const [isButtonPressed, setIsButtonPressed] = useState(false);
  const [rawState, setRawState] = useState<unknown>("Waiting for connection...");

  // The Phidget channel object — kept in a ref so re-renders don't recreate it
  const digitalInputRef = useRef<phidget22.DigitalInput | null>(null);

  function updateRawStatePanel(stateObject: unknown) {
    setRawState(stateObject);
  }

  async function connectToPhidgetServer(address: string, port: number) {
    const connection = new phidget22.NetworkConnection({
      hostname: address,
      port: port,
      onError: (code, message) => updateRawStatePanel({ connectionError: { code, message } }),
      onConnect: () => updateRawStatePanel({ status: "Connected" }),
      onDisconnect: () => {
        setIsConnected(false);
        updateRawStatePanel({ status: "Disconnected from server" });
      },
    });

    await connection.connect();

    const digitalInput = new phidget22.DigitalInput();
    digitalInputRef.current = digitalInput;

    digitalInput.isHubPortDevice = true;
    digitalInput.hubPort = 0;

    // Any channel on any hub connected to the server — adjust if you need
    // to target a specific device/channel.
    digitalInput.onAttach = () => {
      updateRawStatePanel({
        status: "Attached",
        deviceName: digitalInput.deviceName,
        serialNumber: digitalInput.deviceSerialNumber,
        channel: digitalInput.channel,
        state: digitalInput.state,
      });
      setIsButtonPressed(digitalInput.state === true);
    };

    digitalInput.onDetach = () => {
      updateRawStatePanel({ status: "Device detached" });
      setIsButtonPressed(false);
    };

    digitalInput.onStateChange = (state) => {
      setIsButtonPressed(!state);
      updateRawStatePanel({
        status: "State change",
        deviceName: digitalInput.deviceName,
        serialNumber: digitalInput.deviceSerialNumber,
        channel: digitalInput.channel,
        state,
        timestamp: new Date().toISOString(),
      });
    };

    await digitalInput.open(5000);

    setIsConnected(true);
  }

  async function disconnectFromPhidgetServer() {
    if (digitalInputRef.current) {
      try {
        await digitalInputRef.current.close();
      } catch (error) {
        // Channel may already be closed — nothing to do here.
      }
      digitalInputRef.current = null;
    }
    setIsButtonPressed(false);
    setIsConnected(false);
    updateRawStatePanel({ status: "Disconnected" });
  }

  async function handleConnectSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const address = serverAddress.trim();
    const port = parseInt(serverPort, 10);

    try {
      updateRawStatePanel({ status: "Connecting..." });
      await connectToPhidgetServer(address, port);
    } catch (error) {
      updateRawStatePanel({ connectionError: String(error) });
      setIsConnected(false);
    }
  }

  return (
    <div className="phidget-page">
      <h1>Phidget Button Monitor</h1>

      <section>
        <form className="connection-form" onSubmit={handleConnectSubmit}>
          <label>
            Server address
            <input
              type="text"
              value={serverAddress}
              onChange={(event) => setServerAddress(event.target.value)}
              disabled={isConnected}
            />
          </label>
          <label>
            Port
            <input
              type="number"
              value={serverPort}
              onChange={(event) => setServerPort(event.target.value)}
              disabled={isConnected}
              style={{ width: "80px" }}
            />
          </label>
          <button type="submit" disabled={isConnected}>
            Connect
          </button>
          <button type="button" disabled={!isConnected} onClick={disconnectFromPhidgetServer}>
            Disconnect
          </button>
        </form>
        <div className="status-line">
          Status: <span className={isConnected ? "connected" : "disconnected"}>
            {isConnected ? "Connected" : "Disconnected"}
          </span>
        </div>
      </section>

      <section>
        <h2>Button State</h2>
        <div id="buttonVisual" className={isButtonPressed ? "pressed" : "neutral"}>
          {isButtonPressed ? "PRESSED" : "NEUTRAL"}
        </div>
      </section>

      <section>
        <h2>Raw Phidget State</h2>
        <div id="rawStatePanel">
          {typeof rawState === "string" ? rawState : JSON.stringify(rawState, null, 2)}
        </div>
      </section>
    </div>
  );
}
